In [2]:
import pandas as pd
import numpy as np
from transformers import AutoModel, AutoTokenizer

In [3]:
tok = AutoTokenizer.from_pretrained('KB/bert-base-swedish-cased', use_fast=False)
model = AutoModel.from_pretrained('KB/bert-base-swedish-cased')

Some weights of the model checkpoint at KB/bert-base-swedish-cased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [4]:
text = 'Idag är det en vacker dag och åren går'
inputs = tok(text, return_tensors='pt')

In [9]:
inputs

{'input_ids': tensor([[    2, 11024,    54,    82,    59,  5197,   342,    36,  2033,   523,
             3]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [6]:
np.array(inputs.input_ids)

array([[    2, 11024,    54,    82,    59,  5197,   342,    36,  2033,
          523,     3]], dtype=int64)

In [8]:
tok.convert_ids_to_tokens(np.array(inputs.input_ids.reshape(-1,)))

['[CLS]',
 'Idag',
 'är',
 'det',
 'en',
 'vacker',
 'dag',
 'och',
 'åren',
 'går',
 '[SEP]']

In [45]:
#generation_output = model.generate(**inputs, return_dict_in_generate=True, output_scores=True)
#generation_output = model.generate(**inputs, return_dict_in_generate=True, output_scores=True)
generation_output = model.generate(**inputs)

C:\ProgramData\Anaconda3\envs\tf38\lib\site-packages\transformers\generation_utils.py:1227: UserWarning: Neither `max_length` nor `max_new_tokens` has been set, `max_length` will default to 20 (`self.config.max_length`). Controlling `max_length` via the config is deprecated and `max_length` will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


AttributeError: 'BaseModelOutputWithPoolingAndCrossAttentions' object has no attribute 'logits'

In [17]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")

inputs = tokenizer("Hello, my dog is cute and ", return_tensors="pt")
generation_output = model.generate(**inputs, return_dict_in_generate=True, output_scores=True)

Downloading:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/665 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/548M [00:00<?, ?B/s]

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [21]:
generation_output['sequences']

tensor([[15496,    11,   616,  3290,   318, 13779,   290,   220, 17479,    13,
           314,  1101,   407,  1654,   611,   673,   338,   257,   922,  3290]])

In [31]:
tokenizer.convert_ids_to_tokens(np.array(generation_output['sequences']).reshape(-1,))

['Hello',
 ',',
 'Ġmy',
 'Ġdog',
 'Ġis',
 'Ġcute',
 'Ġand',
 'Ġ',
 'icky',
 '.',
 'ĠI',
 "'m",
 'Ġnot',
 'Ġsure',
 'Ġif',
 'Ġshe',
 "'s",
 'Ġa',
 'Ġgood',
 'Ġdog']

In [30]:
np.array(generation_output['sequences']).reshape(-1,).shape

(20,)

In [ ]:
model.sample()

In [73]:
# Define the model repo
model_name = "KB/bert-base-swedish-cased" 


# Download pytorch model
model = AutoModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)


# Transform input tokens 
#inputs = tokenizer("Hello world!", return_tensors="pt")
#inputs = tokenizer("Hejsan världen, hur mår ni?", return_tensors="pt")
inputs = tokenizer(XX[0][-513], return_tensors="pt")


# Model apply
outputs = model(**inputs)

Some weights of the model checkpoint at KB/bert-base-swedish-cased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [71]:
outputs

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.2943, -0.2012, -0.6913,  ..., -0.5045,  0.4321,  0.6769],
         [ 0.4604, -0.4728, -0.6486,  ..., -0.1868,  0.2096,  0.3174],
         [ 0.3726, -0.2437,  0.0253,  ...,  0.2651, -0.2276, -0.0822],
         [ 0.1439,  0.0145,  0.1364,  ..., -0.0069, -0.2518,  0.0516],
         [ 0.0547, -0.0091, -0.5462,  ..., -0.9887,  0.4403, -0.0221],
         [-0.1189, -0.1125,  0.0616,  ..., -1.4116,  1.0616, -0.2104]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[ 0.9983,  0.1959,  0.2413, -0.1433,  0.2580, -0.3140, -0.0538, -0.9793,
          0.0919, -0.9953, -0.3450,  0.2627,  0.0420,  0.3956,  0.2524,  0.2016,
         -0.0468,  0.1342, -0.0016,  0.9999,  0.3578, -0.9959,  0.0376,  0.2310,
          0.2986, -0.9915,  0.0830, -0.4094,  0.1406, -0.0293,  0.1867, -0.8586,
         -0.9466, -0.2932, -0.1551,  0.0437,  0.2896,  0.1175, -0.1109, -0.3225,
          0.1050,  0.9597, -0.0784, -0.9516,  

In [69]:
#inputs = tokenizer(XX[0], return_tensors="pt")
inputs = tokenizer('osten är fin', return_tensors="pt")
inputs.input_ids.shape

torch.Size([1, 5])

In [78]:
XX[0][-512:]

'es  directtv  has even launched its own branded dvr at the show with 100-hours of recording capability  instant replay  and a search function. the set can pause and rewind tv for up to 90 hours. and microsoft chief bill gates announced in his pre-show keynote speech a partnership with tivo  called tivotogo  which means people can play recorded programmes on windows pcs and mobile devices. all these reflect the increasing trend of freeing up multimedia so that people can watch what they want  when they want.'

In [30]:
outputs

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.3144,  1.2170, -0.7437,  ...,  0.1700,  0.4669, -0.3115],
         [ 0.6579, -0.3438, -1.4500,  ...,  0.6935,  0.2233,  0.1434],
         [-0.3583,  0.4933, -0.2427,  ...,  1.3677, -0.1086,  0.0453],
         ...,
         [ 0.4378,  0.5330,  0.2467,  ...,  0.4033,  0.4990,  0.0428],
         [ 0.1118,  0.4356,  0.0494,  ...,  0.7913,  0.1189, -0.0349],
         [-0.1026,  0.5173,  0.1724,  ..., -1.0310,  1.6315,  0.3193]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[ 6.7337e-01, -9.9359e-02,  9.6207e-01, -1.4424e-02,  1.9335e-01,
          7.9911e-02, -1.1110e-01, -3.2301e-01,  1.1621e-02, -9.5700e-01,
         -2.5589e-01,  1.8800e-01,  1.3850e-01,  7.1234e-02,  1.3551e-02,
          1.1380e-01,  1.2811e-01,  7.0249e-02,  1.7214e-01,  9.8747e-01,
          3.2745e-01, -9.9781e-01,  5.8720e-02,  2.0472e-01,  6.0160e-02,
         -8.1287e-01, -2.0260e-01, -6.9466e-01,  2.9594e-01, -9.524

In [122]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import FeatureUnion, Pipeline
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier

class NLPTransformer(TransformerMixin):
    def __init__(self):
        print('Init called')
        self.model_name = 'KB/bert-base-swedish-cased'
        self.Bert = AutoModel.from_pretrained(self.model_name)
        self.Tokenizer = AutoTokenizer.from_pretrained(self.model_name)
        
    def fit(self, X, y=None):
        print('Fit called')
        
        
        return self
        
    def transform(self, X):
        print('Transform Called')
       
        # Transform input tokens 
        transformed = []
        for text in X:
            print(f'text: {text}')
            
            inputs = self.Tokenizer(text, return_tensors="pt", padding='max_length', max_length = 512, truncation=True)

            # Run Bert model
            outputs = self.Bert(**inputs)
            #outputs['last_hidden_state'].detach().numpy().reshape(-1,)
            outputs = outputs['pooler_output'].detach().numpy().reshape(-1,)
            print(f'output shape: {outputs.shape}')
            transformed.append(outputs)
        
        transformed = np.array(transformed)
        print(f'transformed.shape: {transformed.shape}')
        
        return transformed

In [131]:
#pipeline = Pipeline([    
#            ('nlpTransformer', NLPTransformer()),
#            ('clf', MultiOutputClassifier(RandomForestClassifier()))])

In [132]:
pipeline = Pipeline([    
            ('nlpTransformer', NLPTransformer()),
            ('clf', RandomForestClassifier())])

Init called


Some weights of the model checkpoint at KB/bert-base-swedish-cased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [48]:
outputs.keys()

odict_keys(['last_hidden_state', 'pooler_output'])

In [50]:
outputs['last_hidden_state'].shape

torch.Size([1, 6, 768])

In [51]:
outputs['pooler_output'].shape

torch.Size([1, 768])

In [56]:
outputs['last_hidden_state']

tensor([[[-0.3144,  1.2170, -0.7437,  ...,  0.1700,  0.4669, -0.3115],
         [ 0.6579, -0.3438, -1.4500,  ...,  0.6935,  0.2233,  0.1434],
         [-0.3583,  0.4933, -0.2427,  ...,  1.3677, -0.1086,  0.0453],
         ...,
         [ 0.4378,  0.5330,  0.2467,  ...,  0.4033,  0.4990,  0.0428],
         [ 0.1118,  0.4356,  0.0494,  ...,  0.7913,  0.1189, -0.0349],
         [-0.1026,  0.5173,  0.1724,  ..., -1.0310,  1.6315,  0.3193]]],
       grad_fn=<NativeLayerNormBackward0>)

In [33]:
outputs['last_hidden_state'].detach().numpy().reshape(-1,).shape

(7680,)

In [ ]:
tokenizer.decode(inputs.input_ids[0])

In [10]:
df = pd.read_csv('bbc-text.csv')

In [11]:
df.head()

category                                               text
0           tech  tv future in the hands of viewers with home th...
1       business  worldcom boss  left books alone  former worldc...
2          sport  tigers wary of farrell  gamble  leicester say ...
3          sport  yeading face newcastle in fa cup premiership s...
4  entertainment  ocean s twelve raids box office ocean s twelve...

In [13]:
df['category'].unique()

array(['tech', 'business', 'sport', 'entertainment', 'politics'],
      dtype=object)

In [15]:
df2 = pd.get_dummies(df, prefix=['category'], columns=['category'])

In [16]:
X = df2['text']

In [20]:
y = df2.drop(columns=['text'])

In [22]:
X

0       tv future in the hands of viewers with home th...
1       worldcom boss  left books alone  former worldc...
2       tigers wary of farrell  gamble  leicester say ...
3       yeading face newcastle in fa cup premiership s...
4       ocean s twelve raids box office ocean s twelve...
                              ...                        
2220    cars pull down us retail figures us retail sal...
2221    kilroy unveils immigration policy ex-chatshow ...
2222    rem announce new glasgow concert us band rem h...
2223    how political squabbles snowball it s become c...
2224    souness delight at euro progress boss graeme s...
Name: text, Length: 2225, dtype: object

In [23]:
y

category_business  category_entertainment  category_politics  \
0                     0                       0                  0   
1                     1                       0                  0   
2                     0                       0                  0   
3                     0                       0                  0   
4                     0                       1                  0   
...                 ...                     ...                ...   
2220                  1                       0                  0   
2221                  0                       0                  1   
2222                  0                       1                  0   
2223                  0                       0                  1   
2224                  0                       0                  0   

      category_sport  category_tech  
0                  0              1  
1                  0              0  
2                  1              0  
3                  1              0  
4                  0              0  
...              ...            ...  
2220               0              0  
2221               0              0  
2222               0              0  
2223               0              0  
2224               1              0  

[2225 rows x 5 columns]

In [46]:
XX = [a for a in X]

In [52]:
len(XX)

2225

In [54]:
XX[1]

'worldcom boss  left books alone  former worldcom boss bernie ebbers  who is accused of overseeing an $11bn (£5.8bn) fraud  never made accounting decisions  a witness has told jurors.  david myers made the comments under questioning by defence lawyers who have been arguing that mr ebbers was not responsible for worldcom s problems. the phone company collapsed in 2002 and prosecutors claim that losses were hidden to protect the firm s shares. mr myers has already pleaded guilty to fraud and is assisting prosecutors.  on monday  defence lawyer reid weingarten tried to distance his client from the allegations. during cross examination  he asked mr myers if he ever knew mr ebbers  make an accounting decision  .  not that i am aware of   mr myers replied.  did you ever know mr ebbers to make an accounting entry into worldcom books   mr weingarten pressed.  no   replied the witness. mr myers has admitted that he ordered false accounting entries at the request of former worldcom chief financi

In [137]:
#output = pipeline.fit(XX[0:5],y.iloc[0:5].values)
output = pipeline.fit(X.iloc[0:5],y.iloc[0:5].values)

Fit called
Transform Called
text: tv future in the hands of viewers with home theatre systems  plasma high-definition tvs  and digital video recorders moving into the living room  the way people watch tv will be radically different in five years  time.  that is according to an expert panel which gathered at the annual consumer electronics show in las vegas to discuss how these new technologies will impact one of our favourite pastimes. with the us leading the trend  programmes and other content will be delivered to viewers via home networks  through cable  satellite  telecoms companies  and broadband service providers to front rooms and portable devices.  one of the most talked-about technologies of ces has been digital and personal video recorders (dvr and pvr). these set-top boxes  like the us s tivo and the uk s sky+ system  allow people to record  store  play  pause and forward wind tv programmes when they want.  essentially  the technology allows for much more personalised tv. the

output shape: (768,)
text: ocean s twelve raids box office ocean s twelve  the crime caper sequel starring george clooney  brad pitt and julia roberts  has gone straight to number one in the us box office chart.  it took $40.8m (£21m) in weekend ticket sales  according to studio estimates. the sequel follows the master criminals as they try to pull off three major heists across europe. it knocked last week s number one  national treasure  into third place. wesley snipes  blade: trinity was in second  taking $16.1m (£8.4m). rounding out the top five was animated fable the polar express  starring tom hanks  and festive comedy christmas with the kranks.  ocean s twelve box office triumph marks the fourth-biggest opening for a december release in the us  after the three films in the lord of the rings trilogy. the sequel narrowly beat its 2001 predecessor  ocean s eleven which took $38.1m (£19.8m) on its opening weekend and $184m (£95.8m) in total. a remake of the 1960s film  starring frank

In [136]:
pipeline.predict_proba(XX[0:10])

Transform Called
text: tv future in the hands of viewers with home theatre systems  plasma high-definition tvs  and digital video recorders moving into the living room  the way people watch tv will be radically different in five years  time.  that is according to an expert panel which gathered at the annual consumer electronics show in las vegas to discuss how these new technologies will impact one of our favourite pastimes. with the us leading the trend  programmes and other content will be delivered to viewers via home networks  through cable  satellite  telecoms companies  and broadband service providers to front rooms and portable devices.  one of the most talked-about technologies of ces has been digital and personal video recorders (dvr and pvr). these set-top boxes  like the us s tivo and the uk s sky+ system  allow people to record  store  play  pause and forward wind tv programmes when they want.  essentially  the technology allows for much more personalised tv. they are also 

output shape: (768,)
text: ocean s twelve raids box office ocean s twelve  the crime caper sequel starring george clooney  brad pitt and julia roberts  has gone straight to number one in the us box office chart.  it took $40.8m (£21m) in weekend ticket sales  according to studio estimates. the sequel follows the master criminals as they try to pull off three major heists across europe. it knocked last week s number one  national treasure  into third place. wesley snipes  blade: trinity was in second  taking $16.1m (£8.4m). rounding out the top five was animated fable the polar express  starring tom hanks  and festive comedy christmas with the kranks.  ocean s twelve box office triumph marks the fourth-biggest opening for a december release in the us  after the three films in the lord of the rings trilogy. the sequel narrowly beat its 2001 predecessor  ocean s eleven which took $38.1m (£19.8m) on its opening weekend and $184m (£95.8m) in total. a remake of the 1960s film  starring frank

output shape: (768,)
text: last star wars  not for children  the sixth and final star wars movie may not be suitable for young children  film-maker george lucas has said.  he told us tv show 60 minutes that revenge of the sith would be the darkest and most violent of the series.  i don t think i would take a five or six-year-old to this   he told the cbs programme  to be aired on sunday. lucas predicted the film would get a us rating advising parents some scenes may be unsuitable for under-13s. it opens in the uk and us on 19 may. he said he expected the film would be classified pg-13 - roughly equivalent to a british 12a rating.  the five previous star wars films have all carried less restrictive pg - parental guidance - ratings in the us. in the uk  they have all been passed u - suitable for all - with the exception of attack of the clones  which got a pg rating in 2002. revenge of the sith - the third prequel to the original 1977 star wars film - chronicles the transformation of the

[array([[0.94, 0.06],
        [0.35, 0.65],
        [0.95, 0.05],
        [0.86, 0.14],
        [0.92, 0.08],
        [0.89, 0.11],
        [0.92, 0.08],
        [0.89, 0.11],
        [0.89, 0.11],
        [0.89, 0.11]]),
 array([[0.91, 0.09],
        [0.91, 0.09],
        [0.89, 0.11],
        [0.92, 0.08],
        [0.36, 0.64],
        [0.8 , 0.2 ],
        [0.78, 0.22],
        [0.73, 0.27],
        [0.76, 0.24],
        [0.61, 0.39]]),
 array([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]),
 array([[0.87, 0.13],
        [0.83, 0.17],
        [0.27, 0.73],
        [0.25, 0.75],
        [0.77, 0.23],
        [0.65, 0.35],
        [0.61, 0.39],
        [0.52, 0.48],
        [0.46, 0.54],
        [0.66, 0.34]]),
 array([[0.28, 0.72],
        [0.91, 0.09],
        [0.89, 0.11],
        [0.97, 0.03],
        [0.95, 0.05],
        [0.66, 0.34],
        [0.69, 0.31],
        [0.86, 0.14],
        [0.89, 0

In [135]:
pipeline.predict_proba(XX[0:10])

Transform Called
text: tv future in the hands of viewers with home theatre systems  plasma high-definition tvs  and digital video recorders moving into the living room  the way people watch tv will be radically different in five years  time.  that is according to an expert panel which gathered at the annual consumer electronics show in las vegas to discuss how these new technologies will impact one of our favourite pastimes. with the us leading the trend  programmes and other content will be delivered to viewers via home networks  through cable  satellite  telecoms companies  and broadband service providers to front rooms and portable devices.  one of the most talked-about technologies of ces has been digital and personal video recorders (dvr and pvr). these set-top boxes  like the us s tivo and the uk s sky+ system  allow people to record  store  play  pause and forward wind tv programmes when they want.  essentially  the technology allows for much more personalised tv. they are also 

output shape: (768,)
text: ocean s twelve raids box office ocean s twelve  the crime caper sequel starring george clooney  brad pitt and julia roberts  has gone straight to number one in the us box office chart.  it took $40.8m (£21m) in weekend ticket sales  according to studio estimates. the sequel follows the master criminals as they try to pull off three major heists across europe. it knocked last week s number one  national treasure  into third place. wesley snipes  blade: trinity was in second  taking $16.1m (£8.4m). rounding out the top five was animated fable the polar express  starring tom hanks  and festive comedy christmas with the kranks.  ocean s twelve box office triumph marks the fourth-biggest opening for a december release in the us  after the three films in the lord of the rings trilogy. the sequel narrowly beat its 2001 predecessor  ocean s eleven which took $38.1m (£19.8m) on its opening weekend and $184m (£95.8m) in total. a remake of the 1960s film  starring frank

output shape: (768,)
text: last star wars  not for children  the sixth and final star wars movie may not be suitable for young children  film-maker george lucas has said.  he told us tv show 60 minutes that revenge of the sith would be the darkest and most violent of the series.  i don t think i would take a five or six-year-old to this   he told the cbs programme  to be aired on sunday. lucas predicted the film would get a us rating advising parents some scenes may be unsuitable for under-13s. it opens in the uk and us on 19 may. he said he expected the film would be classified pg-13 - roughly equivalent to a british 12a rating.  the five previous star wars films have all carried less restrictive pg - parental guidance - ratings in the us. in the uk  they have all been passed u - suitable for all - with the exception of attack of the clones  which got a pg rating in 2002. revenge of the sith - the third prequel to the original 1977 star wars film - chronicles the transformation of the

[array([[0.94, 0.06],
        [0.35, 0.65],
        [0.95, 0.05],
        [0.86, 0.14],
        [0.92, 0.08],
        [0.89, 0.11],
        [0.92, 0.08],
        [0.89, 0.11],
        [0.89, 0.11],
        [0.89, 0.11]]),
 array([[0.91, 0.09],
        [0.91, 0.09],
        [0.89, 0.11],
        [0.92, 0.08],
        [0.36, 0.64],
        [0.8 , 0.2 ],
        [0.78, 0.22],
        [0.73, 0.27],
        [0.76, 0.24],
        [0.61, 0.39]]),
 array([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]),
 array([[0.87, 0.13],
        [0.83, 0.17],
        [0.27, 0.73],
        [0.25, 0.75],
        [0.77, 0.23],
        [0.65, 0.35],
        [0.61, 0.39],
        [0.52, 0.48],
        [0.46, 0.54],
        [0.66, 0.34]]),
 array([[0.28, 0.72],
        [0.91, 0.09],
        [0.89, 0.11],
        [0.97, 0.03],
        [0.95, 0.05],
        [0.66, 0.34],
        [0.69, 0.31],
        [0.86, 0.14],
        [0.89, 0

In [130]:
y.iloc[0:10].values

array([[0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0]], dtype=uint8)

In [100]:
XX[0:2]

['tv future in the hands of viewers with home theatre systems  plasma high-definition tvs  and digital video recorders moving into the living room  the way people watch tv will be radically different in five years  time.  that is according to an expert panel which gathered at the annual consumer electronics show in las vegas to discuss how these new technologies will impact one of our favourite pastimes. with the us leading the trend  programmes and other content will be delivered to viewers via home networks  through cable  satellite  telecoms companies  and broadband service providers to front rooms and portable devices.  one of the most talked-about technologies of ces has been digital and personal video recorders (dvr and pvr). these set-top boxes  like the us s tivo and the uk s sky+ system  allow people to record  store  play  pause and forward wind tv programmes when they want.  essentially  the technology allows for much more personalised tv. they are also being built-in to hig